### ISSUE TITLE
Cannot save edited config file

### ISSUE THREAD

**Issue by zenitogr** [juhamikael/FileOrganizer#1]
I am on windows 11 and on 0.9.0 of FileOrganizer

I wanted to edit the config and save it but in vscode it claims I dont have sufficient rights and try as admin but even as admin it also says insufficient rights!

**Comment by juhamikael** [comment]
Changed the functionality to readt config file from "Users/`<user>`/Documents/FileOrganizer". 
Should work now.

### [Download link to new release v0.9.1](https://github.com/juhamikael/FileOrganizer/releases/tag/v.0.9.1-beta)
